### ISSUE TITLE
1. Mobile Web

### ISSUE THREAD

**Issue by JanaDTitarchuk** [Adalab/project-promo-m-module-1-team-3#6]
#RESOURCES
- [ ]A group name
- [ ]A group claim
- [ ]A group photo
- [ ]A group description
- [ ]Group strengths and weaknesses
- [ ]Group members info: name, photo, social links
- [ ]Mobile design

#Tasks
- [ ]Define content for the web
- [ ]Header of the home page
- [ ]Hero of the home page
- [ ]About us of the home page
- [ ]Strengths & weaknesses of the home page
- [ ]Footer of the home page
